<?php

return [
    's3' => [
        'endpoint' => env('S3_ENDPOINT', 'https://gos3.io'),
        'key' => env('S3_KEY'),
        'secret' => env('S3_SECRET'),
        'bucket' => env('S3_BUCKET', 'wcinfo'),
        'public_url' => rtrim(env('S3_PUBLIC_URL', 'https://wcinfo.eu-central-1.gos3.io/'), '/').'/',
        'region' => env('S3_REGION', 'eu'),
        'use_path_style_endpoint' => true,
    ],

    'google' => [
        'api_key' => env('GOOGLE_API_KEY'),
        'monthly_budget' => (float) env('GOOGLE_MONTHLY_BUDGET', 20.0),
        'nearby_cache_days' => (int) env('GOOGLE_NEARBY_CACHE_DAYS', 30),
    ],

    'gemini' => [
        'api_key' => env('GEMINI_API_KEY'),
        'model' => env('GEMINI_MODEL', 'gemini-3.6-flash'),
    ],

    'cors' => [
        'allowed_origins' => env('CORS_ALLOWED_ORIGINS', '*'),
    ],

    'admin_notification_email' => env('ADMIN_NOTIFICATION_EMAIL', 'hi@wc-info.org'),

    'smtp' => [
        'host' => env('SMTP_HOST', 'smtp.example.com'),
        'port' => (int) env('SMTP_PORT', 465),
        'user' => env('SMTP_USER'),
        'password' => env('SMTP_PASSWORD'),
        'encryption' => env('SMTP_ENCRYPTION', 'ssl'),
    ],

    'sender_mail' => env('SENDER_MAIL', 'hallo@wc-info.de'),

    'admin' => [
        'user' => env('ADMIN_USER', 'admin'),
        'password' => env('ADMIN_PASSWORD', 'secret'),
    ],

    'admin_hash_secret' => env('ADMIN_HASH_SECRET', ''), // prefix salt used for qualify/delete links
    'admin_hash_secret2' => env('ADMIN_HASH_SECRET2', ''), // suffix salt

    'discover' => [
        'limit' => (int) env('DISCOVER_PLACES_LIMIT', 500),
        'radius' => (int) env('DISCOVER_PLACES_RADIUS', 2000),
        'cache_days' => (int) env('DISCOVER_PLACES_CACHE_DAYS', 30),
    ],

    'public_accessible_types' => [
        // Transit & Transport
        'train_station',
        'subway_station',
        'light_rail_station',
        'transit_station',
        'transit_depot',
        'bus_station',
        'airport',
        'rest_stop',
        'taxi_stand',

        // Parks, Squares & Nature
        'park',
        'city_park',
        'town_square',
        'natural_feature',
        'campground',
        'rv_park',

        // Civic & Government
        // 'city_hall',
        // 'local_government_office',
        // 'government_office',
        // 'courthouse',
        // 'library',
        // 'post_office',
        'cemetery',

        // Culture & Tourism
        'tourist_attraction',
        // 'museum',
        // 'art_museum',
        // 'planetarium',
        // 'aquarium',
        // 'zoo',
        // 'amusement_park',

        // Large Public Facilities
        'shopping_mall',
        'department_store',
        // 'stadium',
        // 'swimming_pool',
        // 'sports_activity_location',
        'gas_station',
        'parking',
        'parking_lot',
        'public_bathroom',
    ],

    'prioritized_place_types' => [
        // 1. Toilets, Restrooms & Public Baths
        'public_bathroom',
        'public_bath',
        'restroom',
        'toilet',

        // 2. Restaurants, Cafes, Bars & Dining
        'african_restaurant',
        'american_restaurant',
        'asian_fusion_restaurant',
        'asian_restaurant',
        'austrian_restaurant',
        'bar',
        'bar_and_grill',
        'barbecue_restaurant',
        'bavarian_restaurant',
        'beer_garden',
        'bistro',
        'brazilian_restaurant',
        'breakfast_restaurant',
        'brewery',
        'brewpub',
        'british_restaurant',
        'brunch_restaurant',
        'buffet_restaurant',
        'cafe',
        'cafeteria',
        'cantonese_restaurant',
        'chicken_restaurant',
        'chinese_restaurant',
        'cocktail_bar',
        'coffee_shop',
        'croatian_restaurant',
        'deli',
        'dessert_restaurant',
        'dim_sum_restaurant',
        'diner',
        'european_restaurant',
        'falafel_restaurant',
        'family_restaurant',
        'fast_food_restaurant',
        'fine_dining_restaurant',
        'fish_and_chips_restaurant',
        'food_court',
        'french_restaurant',
        'fusion_restaurant',
        'gastropub',
        'german_restaurant',
        'greek_restaurant',
        'halal_restaurant',
        'hamburger_restaurant',
        'hawaiian_restaurant',
        'hot_dog_restaurant',
        'ice_cream_shop',
        'indian_restaurant',
        'internet_cafe',
        'irish_pub',
        'italian_restaurant',
        'japanese_restaurant',
        'juice_shop',
        'kebab_shop',
        'korean_barbecue_restaurant',
        'korean_restaurant',
        'latin_american_restaurant',
        'lebanese_restaurant',
        'lounge_bar',
        'mediterranean_restaurant',
        'mexican_restaurant',
        'middle_eastern_restaurant',
        'mongolian_barbecue_restaurant',
        'night_club',
        'noodle_shop',
        'north_indian_restaurant',
        'pizza_restaurant',
        'polish_restaurant',
        'pub',
        'restaurant',
        'salad_shop',
        'sandwich_shop',
        'seafood_restaurant',
        'shawarma_restaurant',
        'snack_bar',
        'soup_restaurant',
        'spanish_restaurant',
        'sports_bar',
        'steak_house',
        'sushi_restaurant',
        'swiss_restaurant',
        'tapas_restaurant',
        'tea_house',
        'tex_mex_restaurant',
        'thai_restaurant',
        'turkish_restaurant',
        'vegan_restaurant',
        'vegetarian_restaurant',
        'vietnamese_restaurant',
        'western_restaurant',
        'wine_bar',
        'winery',

        // 3. Transit & Transport Hubs & Rest Stops
        'airport',
        'international_airport',
        'bus_station',
        'train_station',
        'subway_station',
        'light_rail_station',
        'transit_station',
        'transit_depot',
        'rest_stop',
        'truck_stop',
        'ferry_service',
        'marina',
        'gas_station',

        // 4. Hotels & Accommodations
        'hotel',
        'resort_hotel',
        'motel',
        'hostel',
        'inn',
        'extended_stay_hotel',
        'lodging',
        'campground',
        'rv_park',

        // 5. Large Retail & Department Stores
        'shopping_mall',
        'department_store',
        'hypermarket',
        'warehouse_store',
        'supermarket',

        // 6. Culture, Entertainment, Attractions & Venues
        'amusement_center',
        'amusement_park',
        'aquarium',
        'arena',
        'art_gallery',
        'art_museum',
        'auditorium',
        'banquet_hall',
        'bowling_alley',
        'casino',
        'castle',
        'cinema',
        'movie_theater',
        'comedy_club',
        'community_center',
        'concert_hall',
        'convention_center',
        'cultural_center',
        'dance_hall',
        'event_venue',
        'history_museum',
        'indoor_playground',
        'live_music_venue',
        'museum',
        'observation_deck',
        'opera_house',
        'performing_arts_theater',
        'planetarium',
        'tourist_attraction',
        'tourist_information_center',
        'visitor_center',
        'water_park',
        'wedding_venue',
        'wildlife_park',
        'zoo',
        'video_arcade',

        // 7. Sports, Swimming & Wellness Facilities
        'adventure_sports_center',
        'fitness_center',
        'golf_course',
        'gym',
        'ice_skating_rink',
        'paintball_center',
        'sauna',
        'ski_resort',
        'spa',
        'sports_activity_location',
        'sports_club',
        'sports_complex',
        'stadium',
        'swimming_pool',
        'wellness_center',

        // 8. Public Infrastructure / Civic / Hospitals
        'library',
        'city_hall',
        'hospital',
        'general_hospital',
        'medical_center',
        'parking_garage',
    ],
];
